### ISSUE TITLE
Unknow errors when ADCP run in shell

### ISSUE THREAD

**Issue by mengskl** [ccsb-scripps/ADCP#4]
I performed  ADCP in shell script which aim to do some high throughput virtual screening. But i found that ADCP did not work in script.

here is my input in command line:
>adcp -t protein.trg -s GGGGGGGG -N 100 -n 2500000 -o output.pdb

The output results can be obtained under the above command.

But ADCP did not work when the same command was written into script:
#!/bin/bash
adcp -t protein.trg -s GGGGGGGG -N 100 -n 2500000 -o output.pdb
run the script by> bash script.sh

The output were show as follow:
Detected 112 cores, request 112 cores, using 112 cores
copying the ramaprob.data file from /software/autodock/crankpep/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/ADCP/ramaprob.data to /test/adcp
Performing search (100 ADCP runs with 2500000 steps each) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
10 ENDED WITH ERROR
10 err
11 ENDED WITH ERROR
11 err
75 ENDED WITH ERROR
75 err
13 ENDED WITH ERROR
13 err
14 ENDED WITH ERROR
14 err
78 ENDED WITH ERROR
78 err
79 ENDED WITH ERROR
79 err
80 ENDED WITH ERROR
80 err
81 ENDED WITH ERROR
81 err
19 ENDED WITH ERROR
19 err
83 ENDED WITH ERROR
83 err
31 ENDED WITH ERROR
31 err
32 ENDED WITH ERROR
32 err
33 ENDED WITH ERROR
33 err
34 ENDED WITH ERROR
34 err
35 ENDED WITH ERROR
35 err
21 ENDED WITH ERROR
21 err
36 ENDED WITH ERROR
36 err
37 ENDED WITH ERROR
37 err
38 ENDED WITH ERROR
38 err
39 ENDED WITH ERROR
39 err
40 ENDED WITH ERROR
40 err
41 ENDED WITH ERROR
41 err
22 ENDED WITH ERROR
22 err
42 ENDED WITH ERROR
42 err
43 ENDED WITH ERROR
43 err
64 ENDED WITH ERROR
64 err
44 ENDED WITH ERROR
44 err
45 ENDED WITH ERROR
45 err
46 ENDED WITH ERROR
46 err
47 ENDED WITH ERROR
47 err
86 ENDED WITH ERROR
86 err
0 ENDED WITH ERROR
0 err
49 ENDED WITH ERROR
49 err
65 ENDED WITH ERROR
65 err
50 ENDED WITH ERROR
50 err
51 ENDED WITH ERROR
51 err
52 ENDED WITH ERROR
52 err
53 ENDED WITH ERROR
53 err
87 ENDED WITH ERROR
87 err
54 ENDED WITH ERROR*
54 err
55 ENDED WITH ERROR*
55 err
66 ENDED WITH ERROR**
66 err
56 ENDED WITH ERROR**
56 err
57 ENDED WITH ERROR***
57 err
58 ENDED WITH ERROR***
58 err
59 ENDED WITH ERROR****
59 err
88 ENDED WITH ERROR****
88 err
60 ENDED WITH ERROR*****
60 err
61 ENDED WITH ERROR*****
61 err
67 ENDED WITH ERROR******
67 err
62 ENDED WITH ERROR******
62 err
63 ENDED WITH ERROR*******
63 err
1 ENDED WITH ERROR********
1 err
2 ENDED WITH ERROR*********
2 err
89 ENDED WITH ERROR********
89 err
3 ENDED WITH ERROR**********
3 err
4 ENDED WITH ERROR**********
4 err
68 ENDED WITH ERROR*********
68 err
5 ENDED WITH ERROR***********
5 err
6 ENDED WITH ERROR************
6 err
7 ENDED WITH ERROR************
7 err
8 ENDED WITH ERROR*************
8 err
9 ENDED WITH ERROR*************
9 err
73 ENDED WITH ERROR*************
73 err
69 ENDED WITH ERROR*************
69 err
74 ENDED WITH ERROR**************
74 err
12 ENDED WITH ERROR**************
12 err
48 ENDED WITH ERROR***************
48 err
76 ENDED WITH ERROR***************
76 err
77 ENDED WITH ERROR****************
77 err
15 ENDED WITH ERROR****************
15 err
16 ENDED WITH ERROR*****************
16 err
70 ENDED WITH ERROR*****************
70 err
17 ENDED WITH ERROR******************
17 err
18 ENDED WITH ERROR******************
18 err
82 ENDED WITH ERROR*******************
82 err
20 ENDED WITH ERROR*******************
20 err
84 ENDED WITH ERROR********************
84 err
85 ENDED WITH ERROR********************
85 err
71 ENDED WITH ERROR*********************
71 err
23 ENDED WITH ERROR*********************
23 err
24 ENDED WITH ERROR**********************
24 err
25 ENDED WITH ERROR**********************
25 err
26 ENDED WITH ERROR***********************
26 err
27 ENDED WITH ERROR***********************
27 err
28 ENDED WITH ERROR************************
28 err
72 ENDED WITH ERROR************************
72 err
29 ENDED WITH ERROR*************************
29 err
30 ENDED WITH ERROR*************************
30 err
94 ENDED WITH ERROR**************************
94 err
95 ENDED WITH ERROR**************************
95 err
96 ENDED WITH ERROR***************************
96 err
97 ENDED WITH ERROR***************************
97 err
98 ENDED WITH ERROR****************************
98 err
99 ENDED WITH ERROR****************************
99 err
90 ENDED WITH ERROR*****************************
90 err
91 ENDED WITH ERROR*****************************
91 err
92 ENDED WITH ERROR******************************
92 err
93 ENDED WITH ERROR******************************
93 err
Docking performed in 2.50 seconds, i.e. 0 hours 00 minutes 02.496685 seconds 
Traceback (most recent call last):
  File "/software/autodock/crankpep/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/ADCP/runADCP.py", line 464, in <module>
    runner(**kw)
  File "/software/autodock/crankpep/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/ADCP/runADCP.py", line 406, in __call__
    runner(**kw)
  File "/software/autodock/crankpep/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/ADCP/clusterADCP.py", line 164, in __call__
    models = Read(syst)
  File "/software/autodock/crankpep/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/MolKit2/__init__.py", line 63, in Read
    mol = readWithPrody(filename, header=header, model=model)
  File "/software/autodock/crankpep/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/MolKit2/__init__.py", line 98, in readWithPrody
    mol.buildBondsByDistance()
  File "/software/autodock/crankpep/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/MolKit2/molecule.py", line 913, in buildBondsByDistance
    bo = self.getBondOrdRadius()
  File "/software/autodock/crankpep/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/MolKit2/molecule.py", line 1286, in getBondOrdRadius
    return self.bo_rad[self._ag.getData('atomicNumber')]
AttributeError: Molecule instance has no attribute '_ag'

=========================================================
All the output file have the same context:
found external potential parameters 1 
found external potential parameters 4 
setting constrained list file constrains
Building protein from sequence: ABCDEFGHIGKLMNGPQRSTGVWGYZ.
Building protein from sequence: ABCDEFGHIGKLMNGPQRSTGVWGYZ (26 amino acids, 1 chains).
ABCDEFGHIGKLMNGPQRSTGVWGYZ 26
INFO: Attempting a serial MC simulation.
eof return
ERROR! ERROR! EOF while reading in from input PDB file.
ramaprob initialise success 

=========================================================

How can i solve this issues?

**Comment by sachinpujeri** [comment]
Even I have the same error 
Can u help whoever has resolved this issue

**Comment by Type59pro** [comment]
run ${ADCP_PATH}/bin/python -c "import sys;print(sys.maxunicode)"

if the output is 1114111, it means you python is using UCS4. you need recomplie numpy from source.


**run:**

# remove numpy
${ADCP_PATH}/bin/python -m pip uninstall numpy

# download numpy source code
wget https://github.com/numpy/numpy/archive/v1.16.6.tar.gz

# extract source code
tar -xvzf v1.16.6.tar.gz

# enter extracted directory
cd numpy-1.16.6

# install the build numpy
${ADCP_PATH}/bin/python -m pip install cython
${ADCP_PATH}/bin/python setup.py build


after completing these steps, run adcp to see if the error has been resolved
