### ISSUE TITLE
ADCP error. The at is "NoneType" in clusterADCP.py line 182

### ISSUE THREAD

**Issue by snowline** [ccsb-scripps/ADCP#6]
[bowei@localhost tar1]$ adcp -t 012_48e65_relaxed_rank_1_model_4_h.trg -s npisdvd -N 2 -n 10 -o 012_48e65_relaxed_rank_1_model_4_h_dock -ref 012_48e65_relaxed_rank_1_model_4_h.pdb
Detected 8 cores, using 8 cores
copying the ramaprob.data file from /home/bowei/ADFRsuite-1.0/CCSBpckgs/ADCP/ramaprob.data to /mnt/work/tar/tar1
Performing search (2 ADCP runs with 10 steps each) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Docking performed in 8.02 seconds, i.e. 0 hours 00 minutes 08.020246 seconds 
Traceback (most recent call last):
  File "/home/bowei/ADFRsuite-1.0/CCSBpckgs/ADCP/runADCP.py", line 464, in <module>
    runner(**kw)
  File "/home/bowei/ADFRsuite-1.0/CCSBpckgs/ADCP/runADCP.py", line 406, in __call__
    runner(**kw)
  File "/home/bowei/ADFRsuite-1.0/CCSBpckgs/ADCP/clusterADCP.py", line 182, in __call__
    modelAtomIndices.append(at.getIndices()[0])
AttributeError: 'NoneType' object has no attribute 'getIndices'

Is there anyone can help us? thanks!!!!

**Comment by qoraj** [comment]
Hello! 

I am having the same problem. The tutorials and everything worked fine, but i am getting the same error as you guys: 

~/ADFR10/bin/adcp -t mthk.trg -s npisdvd -N 20 -n 1000000 -o mthk_docking_ctx -ref mthk_poreH.pdb
Detected 8 cores, using 8 cores
copying the ramaprob.data file from /home/denis/ADFR10/CCSBpckgs/ADCP/ramaprob.data to /mnt/c/Users/denis/Documents/PhD/mthk/bioinformatics/ADCP_docking
Performing search (20 ADCP runs with 1000000 steps each) ...
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Docking performed in 165.40 seconds, i.e. 0 hours 02 minutes 45.404079 seconds
Traceback (most recent call last):
  File "/home/denis/ADFR10/CCSBpckgs/ADCP/runADCP.py", line 464, in <module>
    runner(**kw)
  File "/home/denis/ADFR10/CCSBpckgs/ADCP/runADCP.py", line 406, in __call__
    runner(**kw)
  File "/home/denis/ADFR10/CCSBpckgs/ADCP/clusterADCP.py", line 182, in __call__
    modelAtomIndices.append(at.getIndices()[0])
AttributeError: 'NoneType' object has no attribute 'getIndices'

Did you solve the problem already?

**Comment by liszt-c** [comment]
在linux中使用grep -v命令删除PDB文件的ANISOU属性，这个错误是多余的ANISOU属性造成的。
例如，你的PDB文件中有ANISOU这一行，使用grep -v "ANISOU" 3Q47_rec.pdb > 3Q47_rec.pdb删掉它后续就不会报错了

In linux, run the grep -v command to delete the ANISOU attribute of the PDB file. This error is caused by the redundant ANISOU attribute.
such as: If you have ANISOU in your pdb file, use 'grep -v "ANISOU" 3Q47_rec.pdb > 3Q47_rec.pdb'

**Comment by liszt-c** [comment]
还有一个原因可能使用的是windows系统下的ADCP，其默认生成的PDB文件是UTF-16编码的，需要将其转化为UTF-8编码，或者修改源代码中的文件读取方式。
Another reason may be that you are using ADCP for windows. The default generated PDB file is UTF-16 encoding. You need to convert it to UTF-8 encoding or change the way the file is read in the source code.

**Comment by kaplajon** [comment]
It seems to be some kind of mismatch with the reference. I'm also just a user, but could it be that the reference and target structures are not of equal length? Hydrogens? I haven't used ADCP with a reference myself.

**Comment by liszt-c** [comment]
I think it was a mistake in the docking result. The problem in this step should be the comparison between the docking result and the original structure. I found that the docking result lacked some groups relative to the original peptide structure when this mistake occurred. When using ADCP, only a few peptides were able to docking successfully, and I still don't have a solution.

**Comment by humblebeebio** [comment]
I think you may be using your receptor as your reference when it should be your peptide structure. I had the same issue and error code. Using the peptide structure (the peptide pdbqt file) worked for me.

**Comment by Qingtian-UStAnd** [comment]
I have the same issue. When I didn't use -ref in adcr, it worked, but it actually docked peptide npisdvd from the tutorial, not my peptide sequence. That explained why the docking worked without -ref. So, I changed -s npisdvd to -s "my peptide sequence", and it worked. I know it's been a while, and I hope the problem has been solved somewhere else.
